### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ihollander** [nataliagalan/mod-1-mini-challenge-enumerables#1]
Great job overall using the different enumerable methods, it looks like you have a good handle on the syntax! Your code also looks really clean and well indented, so thanks for making it easy on me to parse. Just a couple pieces of feedback (these are all pretty minor!):

- For the `print_spicy_foods` method, one way of getting the correct number of emoji for the heat level is by doing some string multiplication like this:

```rb
def print_spicy_foods(spicy_foods)
  spicy_foods.map do |menu_item|
   spice_emojis = "🌶" * menu_item[:heat_level]
   puts "#{ menu_item[:name] } (#{ menu_item[:cuisine] }) | Heat Level: #{spice_emojis}"
  end
end
```

- Also for the `print_spicy_foods` method, you can use `.each` instead of `.map` since you aren't using the return value of `map` for anything (your code works fine, but `map` is not the most appropriate method to use in this case).

- For the `get_names` method, you can actually do this without using string interpolation, since `menu_item[:name]` is already a string:

```rb
def get_names(spicy_foods)
  spicy_foods.map do |menu_item|
   menu_item[:name]
  end
end
```

- Lastly, in your find method, you could simplify the code in the block - all `.find` needs is a true or false condition to know what it should return. So you could also write it like this:

```
def get_spicy_food_by_cuisine(spicy_foods, cuisine)
  spicy_foods.find do | menu_item |
    menu_item[:cuisine] == cuisine
  end
end
```

**Comment by nataliagalan** [comment]
wow thank you so much for the feedback, Ian! It really helps me a lot. Still learning to keep things as simple as possible. Would it be okay to update my code with your recommendations?

**Comment by ihollander** [comment]
For sure! Glad the feedback is helpful. Definitely feel free to update the code with what I mentioned, but no worries if you don't have time - just keep those things in mind when you're using these methods in the future. Great work again!
